### PR TITLE
Updated Twitter blur functionality

### LINKED ISSUE #97: [BUG] - Extension does not blur images on Twitter
### Description

Media such as images, gifs and video are not being blurred in tweets. Only text is currently being blurred.

### Reproduction URL

_No response_

### Reproduction steps

```bash
1. Add words to Politicry blocked list
2. Enable Politicry for Twitter
3. Go to https://twitter.com/explore
4. Search a hashtag that may contain tweets relevant to the blocked words
```

### Screenshots

image

### Logs

_No response_

### PR DESCRIPTION
**Pull request by k1dubv1**
## Todo

- [x] Fix Twitter blur functionality by blurring all parts of the tweet
- [x] Increase blur to accommodate for video/images

## Motivation

Politicry only blurs the text for Twitter. The user is still able to see other parts of the tweet that they may not like to see such as graphic/unwanted video and images 

## Summary of changes

Changed search to search for each `'article'` rather than each `'div[lang="en"]'` in `extension\public\worker\twitter.js`

## Attached GitHub issue

Closes #97 

### Documentation

- [x] New functions and methods have additional comments added to document their usage

### Local Build

- [x] Extension has been tested to build correctly `cd extension && yarn && yarn build`

### GitHub

- [x] Target branch has been set correctly
- [x] PR has been rebased onto target branch
- [x] PR has been assigned an owner
- [x] Author has performed a self-review of the code
- [x] Removed the WIP message from the top of this PR

### CODE REVIEW

**Comment by k1dubv1** [comment]
Note on number of commits: Created a new fork and laptop has no storage space remaining so I cannot install cypress for the repository (so I cant test anything. The only way that I can see if the tests pass is to push to GitHub). Cannot free up any more space - have done so 4 times over the past month.

**Review by Destiny-02 — CHANGES_REQUESTED** [review]
Nice fix! I've tested it and it works on my side too. 

Are you able to lower the blur effect? Previously, it was set to a high value because it wasn't enough to completely blur the text. Now that the whole post is blurred, I don't think we need the blur to be so extreme. You might need to experiment with what blur value works best for both text and image. Alternatively, you could blur these separately. 

See comment where this was discussed: https://github.com/se310-t6/politicry/pull/81#discussion_r979342501

image

**Comment by k1dubv1** [comment]
> Nice fix! I've tested it and it works on my side too.
> 
> Are you able to lower the blur effect? Previously, it was set to a high value because it wasn't enough to completely blur the text. Now that the whole post is blurred, I don't think we need the blur to be so extreme. You might need to experiment with what blur value works best for both text and image. Alternatively, you could blur these separately.
> 
> See comment where this was discussed: [#81 (comment)](https://github.com/se310-t6/politicry/pull/81#discussion_r979342501)
> 
> image

I purposely increased the blur because the images and videos were not being blurred enough and they were still able to be made out. IIRC instagram is on 30px so its nowhere near as blurry as that (I've set this one to 20px after some playing around with it.) Any less and the image becomes somewhat recognisable.

**Comment by Destiny-02** [comment]
> > Nice fix! I've tested it and it works on my side too.
> > Are you able to lower the blur effect? Previously, it was set to a high value because it wasn't enough to completely blur the text. Now that the whole post is blurred, I don't think we need the blur to be so extreme. You might need to experiment with what blur value works best for both text and image. Alternatively, you could blur these separately.
> > See comment where this was discussed: [#81 (comment)](https://github.com/se310-t6/politicry/pull/81#discussion_r979342501)
> > image
> 
> I purposely increased the blur because the images and videos were not being blurred enough and they were still able to be made out. IIRC instagram is on 30px so its nowhere near as blurry as that (I've set this one to 20px after some playing around with it.) Any less and the image becomes somewhat recognisable.

I see. It is better to over-blur than to under-blur and risk having a recognisable and unwanted post.

**Review by Destiny-02 — APPROVED** [review]

**Pull request merged**
