### PR TITLE
Refactor backend to application pattern

### LINKED ISSUE #15: Refactor backend to use application factory pattern
The backend is currently quite generically implemented. It would be better to switch to a known pattern, e.g. the [application factory](https://flask.palletsprojects.com/en/2.2.x/patterns/appfactories/) pattern. 
At the same time it'll make sense to alter the database solution to a true ORM, such as flask-sqlalchemy. Furthermore, switching to application factory pattern should make testing much cleaner with pytest.

### PR DESCRIPTION
**Pull request by JosiahBull**
Refactored the backend to application factory pattern.
Tasks:
- [x] Refactored backend
- [x] Add some ci/cd actions to validate code moving forwards
- [x] Add some simple tests to build off of, just testing success cases not failure cases
- [x] Update openapi file
- [x] Setup docker-compose file
- [x] #13/#14 must be merged first

Closes #15 and #21
Depends on #13 being merged first

### CODE REVIEW

**Comment by JosiahBull** [comment]
Don't merged until the last 2 tasks have been completed.

**Review by atan958 — DISMISSED** [review]
Lgtm

**Review by lche262 — APPROVED** [review]
Nice work!

**Comment by JosiahBull** [comment]
Rebased onto main to fix merge conflicts, no file changes made.

**Review by Zasheus — APPROVED** [review]
lgtm

**Review by atan958 — APPROVED** [review]
lgtm

**Pull request merged**
